name: Apply Labels

on:
  push:
    paths:
      - '.github/labels.yaml'

jobs:
  apply-labels:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install labels script
      run: npm install -g github-label-sync

    - name: Apply labels from .github/labels.yaml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npx github-label-sync --access-token $GITHUB_TOKEN --labels .github/labels.yaml
